#version: '3.7'
#services:
#  master:
#    container_name: master
#    image: redis
#    ports:
#      - 6379:6379
#  slave-a:
#    container_name: slave-a
#    image: redis
#    ports:
#      - 7001:6379
#    volumes:
#      - ./conf:/usr/local/etc/redis/  # 호스트 디렉토리를 컨테이너 내부로 매핑
#    command: redis-server /usr/local/etc/redis/redis.conf  # 컨테이너 내부 경로 사용
#  slave-b:
#    container_name: slave-b
#    image: redis
#    ports:
#      - 7002:6379
#    volumes:
#      - ./conf:/usr/local/etc/redis/  # 동일하게 수정
#    command: redis-server /usr/local/etc/redis/redis.conf

services:
  master:
    container_name: master
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./conf:/usr/local/etc/redis/
    command: redis-server /usr/local/etc/redis/redis.conf

  slave-a:
    container_name: slave-a
    image: redis
    ports:
      - 7001:6379
    volumes:
      - ./conf:/usr/local/etc/redis/
    command: redis-server /usr/local/etc/redis/redis.conf

  slave-b:
    container_name: slave-b
    image: redis
    ports:
      - 7002:6379
    volumes:
      - ./conf:/usr/local/etc/redis/
    command: redis-server /usr/local/etc/redis/redis.conf

  sentinel:
    container_name: redis-sentinel
    image: redis
    ports:
      - 26379:26379
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf  # Sentinel 설정 파일 경로 지정
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel  # Sentinel 모드로 실행


# docker-compose up -d
# docker run redis cat /usr/local/etc/redis/redis.conf > redis.conf
# docker run redis cat redis.conf > /usr/local/etc/redis/redis.conf

# docker exec -it redis-sentinel redis-cli -p 26379 sentinel masters